@baseURL=http://localhost:3001
GET  {{baseURL}}/api/v1/users

####
GET  {{baseURL}}/api/v1/users?role=admin

####
GET  {{baseURL}}/api/v1/users?page=1&size=2
####
GET  {{baseURL}}/api/v1/users/1

####
DELETE {{baseURL}}/api/v1/users/1

####
POST  {{baseURL}}/api/v1/users
Content-Type:  application/json
Accept: application/json

 {
    "id": 28,
    "name": "Alice1",
    "email": "alice@mail.com",
    "password": "1234",
    "roles": [
      {
        "name": "admin"
      }
    ]
 }
####
POST  {{baseURL}}/api/v1/users
Content-Type:  application/json
Accept: application/json

 {
    "id": 28,
    "name": "Alice1",
    "email": "alice@mail.com",
    "password": "1234"
    
 }

####
PUT  {{baseURL}}/api/v1/users/1
Content-Type:  application/json
Accept: application/json

  {
      "name": "AliceUpdated",
      "email": "xxxx",
      "password": "xxxx"
  }

####
PATCH  {{baseURL}}/api/v1/users/1/password
Content-Type:  application/json
Accept: application/json  

 {
    "newPassword": "5678"
 }