GET  http://localhost:3000/api/v1/users
####
GET  http://localhost:3000/api/v1/users/1

####
DELETE  http://localhost:3000/api/v1/users/1

####
POST  http://localhost:3000/api/v1/users
Content-Type:  application/json
Accept: application/json

 {
    "id": 28,
    "name": "Alice1",
    "email": "alice@mail.com",
    "password": "1234",
    "roles": [
      {
        "name": "admin"
      }
    ]
 }
####
POST  http://localhost:3000/api/v1/users
Content-Type:  application/json
Accept: application/json

 {
    "id": 28,
    "name": "Alice1",
    "email": "alice@mail.com",
    "password": "1234"
    
 }

####

PUT  http://localhost:3000/api/v1/users/1
Content-Type:  application/json
Accept: application/json
  
{
      "name": "AliceUpdated",
      "email": "alice@gmail.com",
      "password": "3456"
  }

  