
@baseUrl=http://localhost:3002/api/v1
@accept=application/json
@content-type=application/json
GET  {{baseUrl}}/comptes

####
GET  {{baseUrl}}/comptes/Cpte-001/solde

####
GET  {{baseUrl}}/comptes?type=Epargne

####
GET  {{baseUrl}}/comptes?page=1&size=xxxx

####
GET  {{baseUrl}}/comptes?type=Epargne&page=1&size=2

####
POST  {{baseUrl}}/comptes
Content-Type: {{ content-type}}
Accept: {{accept}}

{
        "titulaire": "",
        "solde": 0,
        "type": "Cheque"

}

####
