
@baseUrl=http://localhost:3002/api/v1
@accept=application/json
@content-type=application/json
GET  {{baseUrl}}/comptes

####
GET  {{baseUrl}}/comptes/Cpte-001/solde

####
POST  {{baseUrl}}/comptes
Content-Type: {{ content-type}}
Accept: {{accept}}

{
        "titulaire": "Baila Wane1"  ,
        "solde": 10000,
        "type": "Cheque"

}
